# Generated by Django 5.1.4 on 2025-01-25 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postermatch',
            unique_together={('base_id', 'match_id')},
        ),
    ]
