# Generated by Django 5.1.4 on 2025-01-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_postermatch_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='TmdbPoster',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100)),
                ('alt', models.CharField(max_length=100)),
                ('youtube_id', models.CharField(max_length=50)),
                ('image_exists', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'tmdb_posters',
            },
        ),
    ]
