# Generated by Django 5.1.4 on 2025-01-25 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tmdbposter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tmdbposter',
            old_name='movie_id',
            new_name='tmdb_id',
        ),
    ]
