# Generated by Django 5.1.4 on 2025-01-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_movie_id_tmdbposter_tmdb_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosterSearch',
            fields=[
                ('base_id', models.IntegerField(primary_key=True, serialize=False)),
                ('matched_ids', models.TextField()),
            ],
            options={
                'db_table': 'poster_searches',
            },
        ),
    ]
